###
GET http://localhost:3000/api/artikel

###
GET http://localhost:3000/api/galeri

###
GET http://localhost:3000/api/artikel/fakultas-biologi-ugm-tambah-tiga-guru-besar
###
GET http://localhost:3000/api/biro/biro-akademik

###
GET http://localhost:3000/api/prodi
###
GET http://localhost:3000/api/fakultas

###
GET http://localhost:3000/api/download

###
GET http://localhost:3000/api/utilities/sejarah