###
GET http://localhost:3000/api/artikel

###
GET http://localhost:3000/api/galeri

###
GET http://localhost:3000/api/artikel/daftar-calon-wisudawanwisudawati-universitas-pgri-yogyakarta-periode-lll-offline-28-juni-2025-tahun-akademik-20242025
###
GET http://localhost:3000/api/biro/biro-akademik

###
GET http://localhost:3000/api/prodi
###
GET http://localhost:3000/api/fakultas

###
GET http://localhost:3000/api/download

###
GET http://localhost:3000/api/utilities/sejarah

###
GET http://localhost:3000/api/struktur-organisasi

###
GET https://stkip.ac.id/api/struktur-organisasi