###
GET http://localhost:3000/api/artikel

###
GET http://localhost:3000/api/galeri

###
GET http://localhost:3000/api/artikel/daftar-calon-wisudawanwisudawati-universitas-pgri-yogyakarta-periode-lll-offline-28-juni-2025-tahun-akademik-20242025
###
GET http://localhost:3000/api/biro/biro-akademik

###
GET http://localhost:3000/api/prodi
###
GET http://localhost:3000/api/

###
GET http://localhost:3000/api/download

###
GET http://localhost:3000/api/utilities/sejarah

###
GET http://localhost:3000/api/struktur-organisasi

###
GET https://stkip.ac.id/api/struktur-organisasi
 
###
GET http://localhost:3000/api/alumni

###
GET http://localhost:3000/api/listukm
###
GET http://localhost:3000/api/prodi-detail/prodi-s1-akuntansis


###
GET https://admin.stkip.ac.id/api/artikel/menyelenggarakan-ami-stkip-tual-perkuat-kelembagaan


###
GET https://stkip.ac.id/api/artikel?kategori=Pengumuman&search=&page=1&limit=6


###
GET https://stkip.ac.id/api/utilities

###
GET https://stkip.ac.id/api/alumni